### ISSUE TITLE
Create permanent chart cache

### ISSUE THREAD

**Issue by bkuschel** [qlik-oss/qliksense-k8s#111]
Current, chart cache is being built during the initial run of kustomize and stored in the OS tmp directory. 
In order to sever the dependency to the chart repo during a kustomize run completely, it would be preferable to check in the chart cache, as a given version of qliksense-k8s is always dependent on a specific version anyway.

To do this:
- In the CI job that integrates a new version of the helm chart from artifactory, fetch and untar the chart of charts' subcharts into top level `charts` directoy (eg. `charts/audit`)
- The helm chart resource for each component needs to change from eg:
```yaml
apiVersion: qlik.com/v1
kind: HelmChart
metadata:
  name: audit
subChart: audit
releaseName: audit
```
to
```yaml
apiVersion: qlik.com/v1
kind: HelmChart
metadata:
  name: audit
chartHome: ../../charts/audit
releaseName: audit
```
- The transformers directory contains two files that need to change `fullpath.yaml`:
```yaml
apiVersion: qlik.com/v1
kind: FullPath
metadata:
  name: fullpath
fieldSpecs:
- kind: SelectivePatch
  path: patches/path
- kind: SelectivePatch
  path: patches/patches
- kind: HelmChart
  path: chartHome
```
- and `qseokversion.yaml`:
```yaml
 
apiVersion: qlik.com/v1
kind: SelectivePatch
metadata:
  name: qseokversion
enabled: true
patches:
- target:
    kind: HelmChart
  patch: |-
    apiVersion: qlik.com/v1
    kind: HelmChart
    metadata:
      name: helmchart
    releaseNamespace: default
```
